import { Food, FoodGroup } from "../../store/food-slice";

/* emailjs.send constans */
export const MY_SERVICE_ID = "service_5aopvtj";
export const MY_REGISTRATION_TEMPLATE_ID = "template_tkqfwuh";
export const MY_LOSTPASSWORD_TEMPLATE_ID = "template_cy0csxc";
export const MY_PUBLIC_KEY = "spbia2xqnaePNp_0N";

/* database path  */
export const DB_PATH =
    "https://pizzeria-39338-default-rtdb.europe-west1.firebasedatabase.app";

/* Demo user */
export const DEMO_EMAIL = "demo@ludasmeggyes.hu";

/* tokens */
export const HOURS_TO_SAVE_CARTS_DATA = 2;
export const HOURS_TO_SAVE_USERS_DATA = 2;

/* to encrypt */
export const SECRET_PASS = "R4tV56xs42t2W";

/* dummy foods data */
export const DUMMY_PRODUCTS: Food[] = [
    {
        id: 1,
        name: "Margaréta pizza",
        description: "paradicsomszósz, paradicsom, bazsalikom, kevert sajt",
        group: "Pizza",
        hasChildrenServingSize: false,
        varieties: [
            { id: 1, name: "23 cm", price: 2590 },
            { id: 2, name: "32 cm", price: 3100 },
            { id: 3, name: "36 cm", price: 3900 },
        ],
        extras: [
            { id: 1, name: "lila hagyma", price: 50 },
            { id: 2, name: "paradicsom szeletek", price: 150 },
            { id: 3, name: "ananász", price: 150 },
            { id: 4, name: "gomba", price: 100 },
            { id: 5, name: "olivabogyó", price: 250 },
            { id: 6, name: "sonka", price: 200 },
            { id: 7, name: "szalámi", price: 180 },
            { id: 8, name: "fűszeres kolbász", price: 220 },
            { id: 9, name: "kukorica", price: 120 },
            { id: 10, name: "olívaolaj", price: 100 },
            { id: 11, name: "rozmaring", price: 50 },
            { id: 12, name: "fokhagyma", price: 50 },
            { id: 13, name: "jalapeno", price: 150 },
            { id: 14, name: "olívabogyó töltelékkel", price: 300 },
            { id: 15, name: "szárított paradicsom", price: 180 },
            { id: 16, name: "parmezán sajt", price: 250 },
            { id: 17, name: "rucola", price: 120 },
            { id: 18, name: "paprika", price: 80 },
            { id: 19, name: "kapor", price: 70 },
            { id: 20, name: "mozzarella", price: 200 },
            { id: 21, name: "feta sajt", price: 280 },
            { id: 22, name: "szósz extra mennyiség", price: 50 },
            { id: 23, name: "cheddar sajt", price: 240 },
            { id: 24, name: "bazsalikom", price: 60 },
            { id: 25, name: "sült hagyma", price: 100 },
        ],
        packagingFee: 100,
    },
    {
        id: 2,
        name: "Hawaii pizza",
        description: "paradicsomszósz, sonka, ananász, kevert sajt",
        group: "Pizza",
        hasChildrenServingSize: false,
        varieties: [
            { id: 1, name: "23 cm", price: 2250 },
            { id: 2, name: "32 cm", price: 2800 },
            { id: 3, name: "36 cm", price: 3550 },
        ],
        extras: [
            { id: 1, name: "lila hagyma", price: 50 },
            { id: 2, name: "paradicsom szeletek", price: 150 },
            { id: 3, name: "ananász", price: 150 },
            { id: 4, name: "gomba", price: 100 },
            { id: 5, name: "olivabogyó", price: 250 },
            { id: 6, name: "sonka", price: 200 },
            { id: 7, name: "szalámi", price: 180 },
            { id: 8, name: "fűszeres kolbász", price: 220 },
            { id: 9, name: "kukorica", price: 120 },
            { id: 10, name: "olívaolaj", price: 100 },
            { id: 11, name: "rozmaring", price: 50 },
            { id: 12, name: "fokhagyma", price: 50 },
            { id: 13, name: "jalapeno", price: 150 },
            { id: 14, name: "olívabogyó töltelékkel", price: 300 },
            { id: 15, name: "szárított paradicsom", price: 180 },
            { id: 16, name: "parmezán sajt", price: 250 },
            { id: 17, name: "rucola", price: 120 },
            { id: 18, name: "paprika", price: 80 },
            { id: 19, name: "kapor", price: 70 },
            { id: 20, name: "mozzarella", price: 200 },
            { id: 21, name: "feta sajt", price: 280 },
            { id: 22, name: "szósz extra mennyiség", price: 50 },
            { id: 23, name: "cheddar sajt", price: 240 },
            { id: 24, name: "bazsalikom", price: 60 },
            { id: 25, name: "sült hagyma", price: 100 },
        ],
        packagingFee: 100,
    },
    {
        id: 3,
        name: "Pepperoni pizza",
        description: "paradicsomszósz, pepperoni, mozzarella",
        group: "Pizza",
        hasChildrenServingSize: false,
        varieties: [
            { id: 1, name: "23 cm", price: 2750 },
            { id: 2, name: "32 cm", price: 3300 },
            { id: 3, name: "36 cm", price: 4150 },
        ],
        extras: [
            { id: 1, name: "lila hagyma", price: 50 },
            { id: 2, name: "paradicsom szeletek", price: 150 },
            { id: 3, name: "ananász", price: 150 },
            { id: 4, name: "gomba", price: 100 },
            { id: 5, name: "olivabogyó", price: 250 },
            { id: 6, name: "sonka", price: 200 },
            { id: 7, name: "szalámi", price: 180 },
            { id: 8, name: "fűszeres kolbász", price: 220 },
            { id: 9, name: "kukorica", price: 120 },
            { id: 10, name: "olívaolaj", price: 100 },
            { id: 11, name: "rozmaring", price: 50 },
            { id: 12, name: "fokhagyma", price: 50 },
            { id: 13, name: "jalapeno", price: 150 },
            { id: 14, name: "olívabogyó töltelékkel", price: 300 },
            { id: 15, name: "szárított paradicsom", price: 180 },
            { id: 16, name: "parmezán sajt", price: 250 },
            { id: 17, name: "rucola", price: 120 },
            { id: 18, name: "paprika", price: 80 },
            { id: 19, name: "kapor", price: 70 },
            { id: 20, name: "mozzarella", price: 200 },
            { id: 21, name: "feta sajt", price: 280 },
            { id: 22, name: "szósz extra mennyiség", price: 50 },
            { id: 23, name: "cheddar sajt", price: 240 },
            { id: 24, name: "bazsalikom", price: 60 },
            { id: 25, name: "sült hagyma", price: 100 },
        ],
        packagingFee: 100,
    },
    {
        id: 4,
        name: "Gyros pizza",
        description: "paradicsomszósz, gyros hús, hagyma, kevert sajt",
        group: "Pizza",
        hasChildrenServingSize: false,
        varieties: [
            { id: 1, name: "23 cm", price: 2450 },
            { id: 2, name: "32 cm", price: 2900 },
            { id: 3, name: "36 cm", price: 3700 },
        ],
        extras: [
            { id: 1, name: "lila hagyma", price: 50 },
            { id: 2, name: "paradicsom szeletek", price: 150 },
            { id: 3, name: "gomba", price: 100 },
            { id: 4, name: "olivabogyó", price: 250 },
            { id: 5, name: "szalámi", price: 180 },
            { id: 6, name: "kukorica", price: 120 },
            { id: 7, name: "olívaolaj", price: 100 },
            { id: 8, name: "rozmaring", price: 50 },
            { id: 9, name: "fokhagyma", price: 50 },
            { id: 10, name: "jalapeno", price: 150 },
            { id: 11, name: "mozzarella", price: 200 },
            { id: 12, name: "szósz extra mennyiség", price: 50 },
            { id: 13, name: "bazsalikom", price: 60 },
            { id: 14, name: "sült hagyma", price: 100 },
        ],
        packagingFee: 100,
    },
    {
        id: 5,
        name: "Veggie pizza",
        description:
            "paradicsomszósz, paprika, gomba, cukkini, hagyma, kevert sajt",
        group: "Pizza",
        hasChildrenServingSize: false,
        varieties: [
            { id: 1, name: "23 cm", price: 2350 },
            { id: 2, name: "32 cm", price: 2800 },
            { id: 3, name: "36 cm", price: 3600 },
        ],
        extras: [
            { id: 1, name: "lila hagyma", price: 50 },
            { id: 2, name: "paradicsom szeletek", price: 150 },
            { id: 3, name: "gomba", price: 100 },
            { id: 4, name: "olivabogyó", price: 250 },
            { id: 5, name: "szalámi", price: 180 },
            { id: 6, name: "kukorica", price: 120 },
            { id: 7, name: "olívaolaj", price: 100 },
            { id: 8, name: "rozmaring", price: 50 },
            { id: 9, name: "fokhagyma", price: 50 },
            { id: 10, name: "jalapeno", price: 150 },
            { id: 11, name: "mozzarella", price: 200 },
            { id: 12, name: "szósz extra mennyiség", price: 50 },
            { id: 13, name: "bazsalikom", price: 60 },
            { id: 14, name: "sült hagyma", price: 100 },
        ],
        packagingFee: 100,
    },
    {
        id: 6,
        name: "Quattro Formaggi pizza",
        description:
            "paradicsomszósz, gorgonzola, mozzarella, feta sajt, parmezán sajt",
        group: "Pizza",
        hasChildrenServingSize: false,
        varieties: [
            { id: 1, name: "23 cm", price: 2850 },
            { id: 2, name: "32 cm", price: 3400 },
            { id: 3, name: "36 cm", price: 4250 },
        ],
        extras: [
            { id: 1, name: "lila hagyma", price: 50 },
            { id: 2, name: "paradicsom szeletek", price: 150 },
            { id: 3, name: "gomba", price: 100 },
            { id: 4, name: "olivabogyó", price: 250 },
            { id: 5, name: "szalámi", price: 180 },
            { id: 6, name: "kukorica", price: 120 },
            { id: 7, name: "olívaolaj", price: 100 },
            { id: 8, name: "rozmaring", price: 50 },
            { id: 9, name: "fokhagyma", price: 50 },
            { id: 10, name: "jalapeno", price: 150 },
            { id: 11, name: "mozzarella", price: 200 },
            { id: 12, name: "szósz extra mennyiség", price: 50 },
            { id: 13, name: "bazsalikom", price: 60 },
            { id: 14, name: "sült hagyma", price: 100 },
        ],
        packagingFee: 100,
    },
    {
        id: 7,
        name: "Capricciosa pizza",
        description:
            "paradicsomszósz, sonka, gomba, articsóka, fekete olivabogyó, kevert sajt",
        group: "Pizza",
        hasChildrenServingSize: false,
        varieties: [
            { id: 1, name: "23 cm", price: 2650 },
            { id: 2, name: "32 cm", price: 3200 },
            { id: 3, name: "36 cm", price: 4000 },
        ],
        extras: [
            { id: 1, name: "lila hagyma", price: 50 },
            { id: 2, name: "paradicsom szeletek", price: 150 },
            { id: 3, name: "gomba", price: 100 },
            { id: 4, name: "olivabogyó", price: 250 },
            { id: 5, name: "szalámi", price: 180 },
            { id: 6, name: "kukorica", price: 120 },
            { id: 7, name: "olívaolaj", price: 100 },
            { id: 8, name: "rozmaring", price: 50 },
            { id: 9, name: "fokhagyma", price: 50 },
            { id: 10, name: "jalapeno", price: 150 },
            { id: 11, name: "mozzarella", price: 200 },
            { id: 12, name: "szósz extra mennyiség", price: 50 },
            { id: 13, name: "bazsalikom", price: 60 },
            { id: 14, name: "sült hagyma", price: 100 },
        ],
        packagingFee: 100,
    },
    {
        id: 8,
        name: "Quattro Stagioni pizza",
        description:
            "paradicsomszósz, sonka, gomba, articsóka, fekete olivabogyó, kevert sajt",
        group: "Pizza",
        hasChildrenServingSize: false,
        varieties: [
            { id: 1, name: "23 cm", price: 2850 },
            { id: 2, name: "32 cm", price: 3400 },
            { id: 3, name: "36 cm", price: 4250 },
        ],
        extras: [
            { id: 1, name: "lila hagyma", price: 50 },
            { id: 2, name: "paradicsom szeletek", price: 150 },
            { id: 3, name: "gomba", price: 100 },
            { id: 4, name: "olivabogyó", price: 250 },
            { id: 5, name: "szalámi", price: 180 },
            { id: 6, name: "kukorica", price: 120 },
            { id: 7, name: "olívaolaj", price: 100 },
            { id: 8, name: "rozmaring", price: 50 },
            { id: 9, name: "fokhagyma", price: 50 },
            { id: 10, name: "jalapeno", price: 150 },
            { id: 11, name: "mozzarella", price: 200 },
            { id: 12, name: "szósz extra mennyiség", price: 50 },
            { id: 13, name: "bazsalikom", price: 60 },
            { id: 14, name: "sült hagyma", price: 100 },
        ],
        packagingFee: 100,
    },
    {
        id: 9,
        name: "Prosciutto pizza",
        description:
            "paradicsomszósz, sonka, mozzarella, rukkola, parmezán sajt",
        group: "Pizza",
        hasChildrenServingSize: false,
        varieties: [
            { id: 1, name: "23 cm", price: 2750 },
            { id: 2, name: "32 cm", price: 3300 },
            { id: 3, name: "36 cm", price: 4150 },
        ],
        extras: [
            { id: 1, name: "lila hagyma", price: 50 },
            { id: 2, name: "paradicsom szeletek", price: 150 },
            { id: 3, name: "gomba", price: 100 },
            { id: 4, name: "olivabogyó", price: 250 },
            { id: 5, name: "szalámi", price: 180 },
            { id: 6, name: "kukorica", price: 120 },
            { id: 7, name: "olívaolaj", price: 100 },
            { id: 8, name: "rozmaring", price: 50 },
            { id: 9, name: "fokhagyma", price: 50 },
            { id: 10, name: "jalapeno", price: 150 },
            { id: 11, name: "mozzarella", price: 200 },
            { id: 12, name: "szósz extra mennyiség", price: 50 },
            { id: 13, name: "bazsalikom", price: 60 },
            { id: 14, name: "sült hagyma", price: 100 },
        ],
        packagingFee: 100,
    },
    {
        id: 10,
        name: "Diavola pizza",
        description: "paradicsomszósz, pikáns szalámi, mozzarella, jalapeno",
        group: "Pizza",
        hasChildrenServingSize: false,
        varieties: [
            { id: 1, name: "23 cm", price: 2650 },
            { id: 2, name: "32 cm", price: 3200 },
            { id: 3, name: "36 cm", price: 4000 },
        ],
        extras: [
            { id: 1, name: "lila hagyma", price: 50 },
            { id: 2, name: "paradicsom szeletek", price: 150 },
            { id: 3, name: "gomba", price: 100 },
            { id: 4, name: "olivabogyó", price: 250 },
            { id: 5, name: "szalámi", price: 180 },
            { id: 6, name: "kukorica", price: 120 },
            { id: 7, name: "olívaolaj", price: 100 },
            { id: 8, name: "rozmaring", price: 50 },
            { id: 9, name: "fokhagyma", price: 50 },
            { id: 10, name: "jalapeno", price: 150 },
            { id: 11, name: "mozzarella", price: 200 },
            { id: 12, name: "szósz extra mennyiség", price: 50 },
            { id: 13, name: "bazsalikom", price: 60 },
            { id: 14, name: "sült hagyma", price: 100 },
        ],
        packagingFee: 100,
    },
    {
        id: 11,
        name: "Tonno pizza",
        description:
            "paradicsomszósz, tonhal, hagyma, fekete olivabogyó, mozzarella",
        group: "Pizza",
        hasChildrenServingSize: false,
        varieties: [
            { id: 1, name: "23 cm", price: 2650 },
            { id: 2, name: "32 cm", price: 3200 },
            { id: 3, name: "36 cm", price: 4000 },
        ],
        extras: [
            { id: 1, name: "lila hagyma", price: 50 },
            { id: 2, name: "paradicsom szeletek", price: 150 },
            { id: 3, name: "gomba", price: 100 },
            { id: 4, name: "olivabogyó", price: 250 },
            { id: 5, name: "szalámi", price: 180 },
            { id: 6, name: "kukorica", price: 120 },
            { id: 7, name: "olívaolaj", price: 100 },
            { id: 8, name: "rozmaring", price: 50 },
            { id: 9, name: "fokhagyma", price: 50 },
            { id: 10, name: "jalapeno", price: 150 },
            { id: 11, name: "mozzarella", price: 200 },
            { id: 12, name: "szósz extra mennyiség", price: 50 },
            { id: 13, name: "bazsalikom", price: 60 },
            { id: 14, name: "sült hagyma", price: 100 },
        ],
        packagingFee: 100,
    },
    {
        id: 12,
        name: "Frutti di Mare pizza",
        description:
            "paradicsomszósz, tenger gyümölcsei mix, fokhagyma, mozzarella",
        group: "Pizza",
        hasChildrenServingSize: false,
        varieties: [
            { id: 1, name: "23 cm", price: 3150 },
            { id: 2, name: "32 cm", price: 3700 },
            { id: 3, name: "36 cm", price: 4550 },
        ],
        extras: [
            { id: 1, name: "lila hagyma", price: 50 },
            { id: 2, name: "paradicsom szeletek", price: 150 },
            { id: 3, name: "gomba", price: 100 },
            { id: 4, name: "olivabogyó", price: 250 },
            { id: 5, name: "szalámi", price: 180 },
            { id: 6, name: "kukorica", price: 120 },
            { id: 7, name: "olívaolaj", price: 100 },
            { id: 8, name: "rozmaring", price: 50 },
            { id: 9, name: "fokhagyma", price: 50 },
            { id: 10, name: "jalapeno", price: 150 },
            { id: 11, name: "mozzarella", price: 200 },
            { id: 12, name: "szósz extra mennyiség", price: 50 },
            { id: 13, name: "bazsalikom", price: 60 },
            { id: 14, name: "sült hagyma", price: 100 },
        ],
        packagingFee: 100,
    },
    {
        id: 13,
        name: "Caprese pizza",
        description: "paradicsomszósz, mozzarella, paradicsom, bazsalikom",
        group: "Pizza",
        hasChildrenServingSize: false,
        varieties: [
            { id: 1, name: "23 cm", price: 2350 },
            { id: 2, name: "32 cm", price: 2800 },
            { id: 3, name: "36 cm", price: 3600 },
        ],
        extras: [
            { id: 1, name: "lila hagyma", price: 50 },
            { id: 2, name: "paradicsom szeletek", price: 150 },
            { id: 3, name: "gomba", price: 100 },
            { id: 4, name: "olivabogyó", price: 250 },
            { id: 5, name: "szalámi", price: 180 },
            { id: 6, name: "kukorica", price: 120 },
            { id: 7, name: "olívaolaj", price: 100 },
            { id: 8, name: "rozmaring", price: 50 },
            { id: 9, name: "fokhagyma", price: 50 },
            { id: 10, name: "jalapeno", price: 150 },
            { id: 11, name: "mozzarella", price: 200 },
            { id: 12, name: "szósz extra mennyiség", price: 50 },
            { id: 13, name: "bazsalikom", price: 60 },
            { id: 14, name: "sült hagyma", price: 100 },
        ],
        packagingFee: 100,
    },
    {
        id: 14,
        name: "Prosciutto e Funghi pizza",
        description: "paradicsomszósz, sonka, gomba, mozzarella",
        group: "Pizza",
        hasChildrenServingSize: false,
        varieties: [
            { id: 1, name: "23 cm", price: 2550 },
            { id: 2, name: "32 cm", price: 3000 },
            { id: 3, name: "36 cm", price: 3800 },
        ],
        extras: [
            { id: 1, name: "lila hagyma", price: 50 },
            { id: 2, name: "paradicsom szeletek", price: 150 },
            { id: 3, name: "gomba", price: 100 },
            { id: 4, name: "olivabogyó", price: 250 },
            { id: 5, name: "szalámi", price: 180 },
            { id: 6, name: "kukorica", price: 120 },
            { id: 7, name: "olívaolaj", price: 100 },
            { id: 8, name: "rozmaring", price: 50 },
            { id: 9, name: "fokhagyma", price: 50 },
            { id: 10, name: "jalapeno", price: 150 },
            { id: 11, name: "mozzarella", price: 200 },
            { id: 12, name: "szósz extra mennyiség", price: 50 },
            { id: 13, name: "bazsalikom", price: 60 },
            { id: 14, name: "sült hagyma", price: 100 },
        ],
        packagingFee: 100,
    },
    {
        id: 15,
        name: "Falusi tyúkhúsleves",
        description: "leveshússal, vele főtt zöldségekkel és lúdgégetésztával",
        group: "Leves",
        price: 1580,
        hasChildrenServingSize: true,
        priceOfChildrenServingSize: 1100,
        extras: [
            { id: 1, name: "csipőspaprika", price: 250 },
            { id: 2, name: "kenyér szelet", price: 50 },
            { id: 3, name: "tejföl", price: 150 },
            { id: 4, name: "reszelt sajt", price: 200 },
            { id: 5, name: "zöldhagyma", price: 100 },
            { id: 6, name: "fokhagymás kruton", price: 80 },
            { id: 7, name: "paradicsomkocka", price: 120 },
            { id: 8, name: "uborka szelet", price: 70 },
        ],
        packagingFee: 150,
    },
    {
        id: 16,
        name: "Gulyásleves",
        description: "marhahússal, burgonyával és paprikával",
        group: "Leves",
        price: 1850,
        hasChildrenServingSize: true,
        priceOfChildrenServingSize: 1250,
        extras: [
            { id: 1, name: "csipőspaprika", price: 250 },
            { id: 2, name: "kenyér szelet", price: 50 },
            { id: 3, name: "tejföl", price: 150 },
            { id: 4, name: "reszelt sajt", price: 200 },
            { id: 5, name: "zöldhagyma", price: 100 },
            { id: 6, name: "fokhagymás kruton", price: 80 },
            { id: 7, name: "paradicsomkocka", price: 120 },
            { id: 8, name: "uborka szelet", price: 70 },
        ],
        packagingFee: 150,
    },
    {
        id: 17,
        name: "Paradicsomleves",
        description: "friss paradicsomból készült, pirított kenyérrel",
        group: "Leves",
        price: 1250,
        hasChildrenServingSize: true,
        priceOfChildrenServingSize: 900,
        extras: [
            { id: 1, name: "csipőspaprika", price: 250 },
            { id: 2, name: "kenyér szelet", price: 50 },
            { id: 3, name: "tejföl", price: 150 },
            { id: 4, name: "reszelt sajt", price: 200 },
            { id: 5, name: "zöldhagyma", price: 100 },
            { id: 6, name: "fokhagymás kruton", price: 80 },
            { id: 7, name: "paradicsomkocka", price: 120 },
            { id: 8, name: "uborka szelet", price: 70 },
        ],
        packagingFee: 150,
    },
    {
        id: 18,
        name: "Sültkrumplileves",
        description: "sült krumpliból, hagymával és sajttal",
        group: "Leves",
        price: 1420,
        hasChildrenServingSize: true,
        priceOfChildrenServingSize: 990,
        extras: [
            { id: 1, name: "csipőspaprika", price: 250 },
            { id: 2, name: "kenyér szelet", price: 50 },
            { id: 3, name: "tejföl", price: 150 },
            { id: 4, name: "reszelt sajt", price: 200 },
            { id: 5, name: "zöldhagyma", price: 100 },
            { id: 6, name: "fokhagymás kruton", price: 80 },
            { id: 7, name: "paradicsomkocka", price: 120 },
            { id: 8, name: "uborka szelet", price: 70 },
        ],
        packagingFee: 150,
    },
    {
        id: 19,
        name: "Húsleves gazdagon",
        description: "marhahússal, zöldségekkel és tésztával",
        group: "Leves",
        price: 1680,
        hasChildrenServingSize: true,
        priceOfChildrenServingSize: 1150,
        extras: [
            { id: 1, name: "csipőspaprika", price: 250 },
            { id: 2, name: "kenyér szelet", price: 50 },
            { id: 3, name: "tejföl", price: 150 },
            { id: 4, name: "reszelt sajt", price: 200 },
            { id: 5, name: "zöldhagyma", price: 100 },
            { id: 6, name: "fokhagymás kruton", price: 80 },
            { id: 7, name: "paradicsomkocka", price: 120 },
            { id: 8, name: "uborka szelet", price: 70 },
        ],
        packagingFee: 150,
    },
    {
        id: 20,
        name: "Házi zöldborsóleves",
        description: "friss zöldborsóból készült, füstölt hússal",
        group: "Leves",
        price: 1450,
        hasChildrenServingSize: true,
        priceOfChildrenServingSize: 1000,
        extras: [
            { id: 1, name: "csipőspaprika", price: 250 },
            { id: 2, name: "kenyér szelet", price: 50 },
            { id: 3, name: "tejföl", price: 150 },
            { id: 4, name: "reszelt sajt", price: 200 },
            { id: 5, name: "zöldhagyma", price: 100 },
            { id: 6, name: "fokhagymás kruton", price: 80 },
            { id: 7, name: "paradicsomkocka", price: 120 },
            { id: 8, name: "uborka szelet", price: 70 },
        ],
        packagingFee: 150,
    },
    {
        id: 21,
        name: "Zöldségleves",
        description: "friss zöldségekből készült, petrezselyemmel",
        group: "Leves",
        price: 1350,
        hasChildrenServingSize: true,
        priceOfChildrenServingSize: 950,
        extras: [
            { id: 1, name: "csipőspaprika", price: 250 },
            { id: 2, name: "kenyér szelet", price: 50 },
            { id: 3, name: "tejföl", price: 150 },
            { id: 4, name: "reszelt sajt", price: 200 },
            { id: 5, name: "zöldhagyma", price: 100 },
            { id: 6, name: "fokhagymás kruton", price: 80 },
            { id: 7, name: "paradicsomkocka", price: 120 },
            { id: 8, name: "uborka szelet", price: 70 },
        ],
        packagingFee: 150,
    },
    {
        id: 22,
        name: "Sült csirkecomb",
        description: "Ropogósra sült csirkecomb fűszeres panírban",
        group: "Frissensült",
        price: 1490,
        hasChildrenServingSize: true,
        priceOfChildrenServingSize: 990,
        extras: [
            { id: 1, name: "Fokhagymás joghurt szósz", price: 250 },
            { id: 2, name: "Krumplipüré", price: 300 },
            { id: 3, name: "Friss saláta", price: 350 },
        ],
        packagingFee: 100,
    },
    {
        id: 23,
        name: "Rántott szelet",
        description:
            "Sült hús szelet, panírozva, törtburgonyával és párolt zöldségekkel",
        group: "Frissensült",
        price: 1680,
        hasChildrenServingSize: true,
        priceOfChildrenServingSize: 1200,
        extras: [
            { id: 1, name: "Tartár szósz", price: 250 },
            { id: 2, name: "Párolt rizs", price: 300 },
            { id: 3, name: "Friss saláta", price: 350 },
        ],
        packagingFee: 100,
    },
    {
        id: 24,
        name: "Grillezett sertéskaraj",
        description:
            "Grillezett sertéskaraj roppanós serpenyőben sütve, petrezselymes burgonyával",
        group: "Frissensült",
        price: 1890,
        hasChildrenServingSize: true,
        priceOfChildrenServingSize: 1400,
        extras: [
            { id: 1, name: "Mustár-mézes mártás", price: 250 },
            { id: 2, name: "Grillezett zöldségek", price: 350 },
        ],
        packagingFee: 100,
    },
    {
        id: 25,
        name: "Tepsis rántott hal",
        description:
            "Zsírban sütött rántott hal filé friss citrommal, petrezselymes krumplival",
        group: "Frissensült",
        price: 1990,
        hasChildrenServingSize: true,
        priceOfChildrenServingSize: 1500,
        extras: [
            { id: 1, name: "Tartár szósz", price: 250 },
            { id: 2, name: "Ropogós sültkrumpli", price: 300 },
            { id: 3, name: "Friss saláta", price: 350 },
        ],
        packagingFee: 100,
    },
    {
        id: 26,
        name: "Bécsi szelet",
        description:
            "Sertésszelet rántva, petrezselymes burgonyával és párolt zöldségekkel",
        group: "Frissensült",
        price: 1790,
        hasChildrenServingSize: true,
        priceOfChildrenServingSize: 1300,
        extras: [
            { id: 1, name: "Tartár szósz", price: 250 },
            { id: 2, name: "Csemege uborka", price: 200 },
            { id: 3, name: "Friss saláta", price: 350 },
        ],
        packagingFee: 100,
    },
    {
        id: 27,
        name: "Grillezett csirkemell",
        description:
            "Grillezett csirkemell filé fűszeres marinádban, jázminrizzsel és párolt zöldségekkel",
        group: "Frissensült",
        price: 1690,
        hasChildrenServingSize: true,
        priceOfChildrenServingSize: 1200,
        extras: [
            { id: 1, name: "Szezámmagos szósz", price: 250 },
            { id: 2, name: "Grillezett zöldségek", price: 350 },
        ],
        packagingFee: 100,
    },
    {
        id: 28,
        name: "Sült tarja",
        description:
            "Ropogósra sült sertéstarja mustáros-mézes glazúrral, burgonyapürével és párolt zöldségekkel",
        group: "Frissensült",
        price: 1880,
        hasChildrenServingSize: true,
        priceOfChildrenServingSize: 1400,
        extras: [
            { id: 1, name: "Mustár-mézes mártás", price: 250 },
            { id: 2, name: "Párolt káposzta", price: 300 },
            { id: 3, name: "Friss saláta", price: 350 },
        ],
        packagingFee: 100,
    },
    {
        id: 29,
        name: "Rántott sajt",
        description: "Rántott sajtszeletek friss salátával és áfonya mártással",
        group: "Frissensült",
        price: 1390,
        hasChildrenServingSize: true,
        priceOfChildrenServingSize: 900,
        extras: [
            { id: 1, name: "Áfonya mártás", price: 250 },
            { id: 2, name: "Ropogós sültkrumpli", price: 300 },
        ],
        packagingFee: 100,
    },
    {
        id: 30,
        name: "Bolognai spagetti",
        description:
            "Ízletes bolognai szósszal és frissen reszelt parmezánnal tálalva.",
        group: "Tészta",
        price: 1580,
        hasChildrenServingSize: true,
        priceOfChildrenServingSize: 1100,
        extras: [
            {
                id: 1,
                name: "Extra parmezán",
                price: 200,
            },
        ],
        packagingFee: 100,
    },
    {
        id: 31,
        name: "Carbonara spagetti",
        description:
            "Ínycsiklandozó carbonara szósszal és ropogós bacon chips-szel tálalva.",
        group: "Tészta",
        price: 1450,
        hasChildrenServingSize: true,
        priceOfChildrenServingSize: 1000,
        extras: [
            {
                id: 1,
                name: "Extra bacon",
                price: 300,
            },
            {
                id: 2,
                name: "Extra tojás",
                price: 150,
            },
        ],
        packagingFee: 100,
    },
    {
        id: 32,
        name: "Napolitana spagetti",
        description:
            "Tradicionális nápolyi paradicsom szósszal, friss bazsalikommal és mozzarellával tálalva.",
        group: "Tészta",
        price: 1350,
        hasChildrenServingSize: true,
        priceOfChildrenServingSize: 900,
        extras: [
            {
                id: 1,
                name: "Extra mozzarella",
                price: 250,
            },
        ],
        packagingFee: 100,
    },
    {
        id: 33,
        name: "Pesto spagetti",
        description:
            "Friss bazsalikom és fenyőmag pesto szósszal, valamint parmezán forgáccsal tálalva.",
        group: "Tészta",
        price: 1550,
        hasChildrenServingSize: true,
        priceOfChildrenServingSize: 1100,
        extras: [
            {
                id: 1,
                name: "Extra fenyőmag",
                price: 200,
            },
            {
                id: 2,
                name: "Extra parmezán forgács",
                price: 150,
            },
        ],
        packagingFee: 100,
    },
    {
        id: 34,
        name: "Gombás-tejszínes spagetti",
        description:
            "Szaftos gombamártás tejszínnel, frissen vágott petrezselyemmel és reszelt sajttal tálalva.",
        group: "Tészta",
        price: 1380,
        hasChildrenServingSize: true,
        priceOfChildrenServingSize: 950,
        extras: [
            {
                id: 1,
                name: "Extra gomba",
                price: 200,
            },
            {
                id: 2,
                name: "Extra tejföl",
                price: 150,
            },
        ],
        packagingFee: 100,
    },
    {
        id: 35,
        name: "Fűszeres csirkeszószos tészta",
        description:
            "Csípős csirkeszósz chilivel, friss zöldségekkel és pirított szezámmaggal tálalva.",
        group: "Tészta",
        price: 1650,
        hasChildrenServingSize: true,
        priceOfChildrenServingSize: 1200,
        extras: [
            {
                id: 1,
                name: "Extra csirkehús",
                price: 300,
            },
            {
                id: 2,
                name: "Extra chiliszósz",
                price: 150,
            },
        ],
        packagingFee: 100,
    },
    {
        id: 36,
        name: "Spenótos-ricottás tortellini",
        description:
            "Friss spenót és lágy ricotta töltelékkel, parmezánnal és vajas szósszal tálalva.",
        group: "Tészta",
        price: 1480,
        hasChildrenServingSize: true,
        priceOfChildrenServingSize: 1050,
        extras: [
            {
                id: 1,
                name: "Extra spenót",
                price: 200,
            },
            {
                id: 2,
                name: "Extra ricotta",
                price: 150,
            },
        ],
        packagingFee: 100,
    },
    {
        id: 37,
        name: "Sajtos hamburger",
        description:
            "Szaftos marhahús pihentetett sajttal, friss salátával és paradicsomszeletekkel, ropogós zsemlén tálalva.",
        group: "Hamburger",
        price: 1990,
        hasChildrenServingSize: false,
        extras: [
            { id: 1, name: "Extra sajt", price: 100 },
            { id: 2, name: "Bacon", price: 150 },
        ],
        packagingFee: 100,
    },
    {
        id: 38,
        name: "Dupla sajtos hamburger",
        description:
            "Két szaftos marhahús pogácsa pihentetett sajttal, friss salátával, paradicsomszeletekkel, hagymával és különleges szósszal, szezámmagos zsemlén tálalva.",
        group: "Hamburger",
        price: 2190,
        hasChildrenServingSize: false,
        extras: [
            { id: 1, name: "Extra sajt", price: 100 },
            { id: 2, name: "Extra bacon", price: 150 },
            { id: 3, name: "Extra hagyma", price: 50 },
        ],
        packagingFee: 100,
    },
    {
        id: 39,
        name: "Csirkés hamburger",
        description:
            "Grillezett csirkemell filé friss salátával, paradicsommal és házi szósszal, lágy zsemlében tálalva.",
        group: "Hamburger",
        price: 1790,
        hasChildrenServingSize: false,
        extras: [
            { id: 1, name: "Extra sajt", price: 100 },
            { id: 2, name: "Extra bacon", price: 150 },
            { id: 3, name: "Extra jalapeno", price: 80 },
        ],
        packagingFee: 100,
    },
    {
        id: 40,
        name: "Vegetáriánus hamburger",
        description:
            "Zöldséges húspótló pogi friss zöldségekkel, avokádókrémmel és vegán majonézzel, teljes kiőrlésű zsemlében tálalva.",
        group: "Hamburger",
        price: 1690,
        hasChildrenServingSize: false,
        extras: [
            { id: 1, name: "Extra vegán sajt", price: 120 },
            { id: 2, name: "Extra guacamole", price: 100 },
            { id: 3, name: "Extra sült gomba", price: 80 },
        ],
        packagingFee: 100,
    },
    {
        id: 41,
        name: "Chilis hamburger",
        description:
            "Marhahús pihentetett sajttal, friss salátával, paradicsommal és pikáns chiliszósszal, chilis zsemlében tálalva.",
        group: "Hamburger",
        price: 2090,
        hasChildrenServingSize: false,
        extras: [
            { id: 1, name: "Extra sajt", price: 100 },
            { id: 2, name: "Extra jalapeno", price: 80 },
            { id: 3, name: "Extra cheddar sajt", price: 120 },
            { id: 4, name: "Extra csípős szósz", price: 50 },
        ],
        packagingFee: 100,
    },
    {
        id: 42,
        name: "Burger Special",
        description:
            "Szaftos marhahús pogácsa, karamellizált hagyma, cheddar sajt, friss saláta és házi szósz, brioche zsemlében tálalva.",
        group: "Hamburger",
        price: 2290,
        hasChildrenServingSize: false,
        extras: [
            { id: 1, name: "Extra bacon", price: 150 },
            { id: 2, name: "Extra jalapeno", price: 80 },
            { id: 3, name: "Extra gombafejek", price: 70 },
            { id: 4, name: "Extra koriander szósz", price: 60 },
        ],
        packagingFee: 100,
    },
    {
        id: 43,
        name: "BBQ hamburger",
        description:
            "Szaftos marhahús pihentetett sajttal, friss salátával, paradicsommal, hagymával és ízletes BBQ szósszal, brioche zsemlében tálalva.",
        group: "Hamburger",
        price: 2090,
        hasChildrenServingSize: false,
        extras: [
            { id: 1, name: "Extra sajt", price: 100 },
            { id: 2, name: "Extra bacon", price: 150 },
            { id: 3, name: "Extra sült hagymakarika", price: 70 },
            { id: 4, name: "Extra BBQ szósz", price: 50 },
        ],
        packagingFee: 100,
    },
    {
        id: 44,
        name: "Görög hamburger",
        description:
            "Szaftos marhahús feta sajttal, friss salátával, paradicsommal, uborkával és tzatzikivel, lágy zsemlében tálalva.",
        group: "Hamburger",
        price: 2090,
        hasChildrenServingSize: false,
        extras: [
            { id: 1, name: "Extra feta sajt", price: 120 },
            { id: 2, name: "Extra olívabogyó", price: 80 },
            { id: 3, name: "Extra tzatziki szósz", price: 60 },
        ],
        packagingFee: 100,
    },
    {
        id: 45,
        name: "Bacon Deluxe",
        description:
            "Szaftos marhahús pihentetett sajttal, friss salátával, paradicsommal, hagymával, bacon szeletekkel és házi szósszal, lágy zsemlében tálalva.",
        group: "Hamburger",
        price: 2290,
        hasChildrenServingSize: false,
        extras: [
            { id: 1, name: "Extra sajt", price: 100 },
            { id: 2, name: "Extra jalapeno", price: 80 },
            { id: 3, name: "Extra sült hagymakarika", price: 70 },
            { id: 4, name: "Extra BBQ szósz", price: 50 },
            { id: 5, name: "Extra tojás", price: 90 },
        ],
        packagingFee: 100,
    },
    {
        id: 46,
        name: "Hawaii hamburger",
        description:
            "Szaftos marhahús pihentetett sajttal, friss salátával, paradicsommal, ananásszal és sült sonkával, lágy zsemlében tálalva.",
        group: "Hamburger",
        price: 2090,
        hasChildrenServingSize: false,
        extras: [
            { id: 1, name: "Extra sajt", price: 100 },
            { id: 2, name: "Extra jalapeno", price: 80 },
            { id: 3, name: "Extra ananász", price: 60 },
        ],
        packagingFee: 100,
    },
    {
        id: 47,
        name: "Csirkesaláta",
        description: "Friss zöldségekkel és sült csirkemellel.",
        group: "Saláta",
        price: 1990,
        hasChildrenServingSize: false,
        extras: [
            {
                id: 1,
                name: "Tört tortilla",
                price: 200,
            },
            {
                id: 2,
                name: "Grillezett paprika",
                price: 150,
            },
        ],
        packagingFee: 120,
    },
    {
        id: 48,
        name: "Görög saláta",
        description:
            "Tradicionális görög saláta feta sajttal és olívabogyóval.",
        group: "Saláta",
        price: 1790,
        hasChildrenServingSize: false,
        extras: [
            {
                id: 1,
                name: "Olívabogyó",
                price: 100,
            },
            {
                id: 2,
                name: "Feta sajt",
                price: 250,
            },
        ],
        packagingFee: 120,
    },
    {
        id: 49,
        name: "Cézár saláta",
        description:
            "Klasszikus cézár saláta öntettel és pirított kenyérkockákkal.",
        group: "Saláta",
        price: 1690,
        hasChildrenServingSize: false,
        extras: [
            {
                id: 1,
                name: "Parmezán sajt",
                price: 180,
            },
            {
                id: 2,
                name: "Pirított csirkehús",
                price: 300,
            },
        ],
        packagingFee: 120,
    },
    {
        id: 50,
        name: "Caprese saláta",
        description: "Friss paradicsom, mozzarella és bazsalikom saláta.",
        group: "Saláta",
        price: 1490,
        hasChildrenServingSize: false,
        extras: [
            {
                id: 1,
                name: "Balzsamecet",
                price: 80,
            },
            {
                id: 2,
                name: "Extra szűz olívaolaj",
                price: 120,
            },
        ],
        packagingFee: 120,
    },
    {
        id: 51,
        name: "Tavaszi saláta",
        description: "Friss tavaszi zöldségekkel és fűszernövényekkel.",
        group: "Saláta",
        price: 1390,
        hasChildrenServingSize: false,
        extras: [
            {
                id: 1,
                name: "Friss koriander",
                price: 90,
            },
            {
                id: 2,
                name: "Citromlé",
                price: 70,
            },
        ],
        packagingFee: 120,
    },
    {
        id: 52,
        name: "Tenger gyümölcsei saláta",
        description: "Friss tenger gyümölcseivel gazdagított saláta.",
        group: "Saláta",
        price: 2090,
        hasChildrenServingSize: false,
        extras: [
            {
                id: 1,
                name: "Rák",
                price: 400,
            },
            {
                id: 2,
                name: "Kagyló",
                price: 350,
            },
        ],
        packagingFee: 120,
    },
    {
        id: 53,
        name: "Mediterrán saláta",
        description: "Mediterrán ízekkel és friss zöldségekkel készült saláta.",
        group: "Saláta",
        price: 1590,
        hasChildrenServingSize: false,
        extras: [
            {
                id: 1,
                name: "Cukkini",
                price: 120,
            },
            {
                id: 2,
                name: "Padlizsán",
                price: 140,
            },
        ],
        packagingFee: 120,
    },
    {
        id: 54,
        name: "Csokoládétorta",
        description:
            "Selymes csokoládétorta házi készítésű csokoládémártással.",
        group: "Desszert",
        price: 1490,
        hasChildrenServingSize: false,
        extras: [
            {
                id: 1,
                name: "Extra csokoládémártás",
                price: 200,
            },
            {
                id: 2,
                name: "Vaníliás hab",
                price: 100,
            },
        ],
        packagingFee: 150,
    },
    {
        id: 55,
        name: "Eperhabos piskóta",
        description: "Friss eperhabbal töltött piskótatorta szelet.",
        group: "Desszert",
        price: 1390,
        hasChildrenServingSize: false,
        extras: [
            {
                id: 1,
                name: "Eperöntet",
                price: 150,
            },
            {
                id: 2,
                name: "Tejszínhab",
                price: 100,
            },
        ],
        packagingFee: 150,
    },
    {
        id: 56,
        name: "Mákos guba",
        description: "Tradicionális mákos guba vaníliaöntettel.",
        group: "Desszert",
        price: 1190,
        hasChildrenServingSize: false,
        extras: [
            {
                id: 1,
                name: "Rum",
                price: 200,
            },
            {
                id: 2,
                name: "Mazsola",
                price: 100,
            },
        ],
        packagingFee: 150,
    },
    {
        id: 57,
        name: "Tiramisu",
        description: "Olasz tiramisu mascarpone krémmel és kakaóporral.",
        group: "Desszert",
        price: 1590,
        hasChildrenServingSize: false,
        extras: [
            {
                id: 1,
                name: "Amaretto",
                price: 250,
            },
            {
                id: 2,
                name: "Pisztácia",
                price: 150,
            },
        ],
        packagingFee: 150,
    },
    {
        id: 58,
        name: "Sütőtök pite",
        description:
            "Sütőtökös töltelékkel készült sütemény, tejszínhabbal tálalva.",
        group: "Desszert",
        price: 1290,
        hasChildrenServingSize: false,
        extras: [
            {
                id: 1,
                name: "Karamellöntet",
                price: 200,
            },
            {
                id: 2,
                name: "Fahéjas porcukor",
                price: 100,
            },
        ],
        packagingFee: 150,
    },
    {
        id: 59,
        name: "Málnás panna cotta",
        description: "Friss málnával díszített panna cotta vaníliaöntettel.",
        group: "Desszert",
        price: 1390,
        hasChildrenServingSize: false,
        extras: [
            {
                id: 1,
                name: "Málnaszósz",
                price: 150,
            },
            {
                id: 2,
                name: "Citromhéj reszelék",
                price: 100,
            },
        ],
        packagingFee: 150,
    },
    {
        id: 60,
        name: "Császármorzsa",
        description:
            "Ropogós császármorzsa porcukorral meghintve, vaníliás öntettel.",
        group: "Desszert",
        price: 1090,
        hasChildrenServingSize: false,
        extras: [
            {
                id: 1,
                name: "Meggybefőtt",
                price: 150,
            },
            {
                id: 2,
                name: "Fahéjas tejföl",
                price: 100,
            },
        ],
        packagingFee: 150,
    },
    {
        id: 61,
        name: "Diós sütemény",
        description:
            "Dióval és mazsolával gazdagított sütemény, csokoládéöntettel.",
        group: "Desszert",
        price: 1290,
        hasChildrenServingSize: false,
        extras: [
            {
                id: 1,
                name: "Tejföl",
                price: 100,
            },
            {
                id: 2,
                name: "Mézeskalács morzsák",
                price: 150,
            },
        ],
        packagingFee: 150,
    },
    {
        id: 62,
        name: "Cseresznyés palacsinta",
        description:
            "Cseresznyével töltött palacsinta porcukorral és tejszínhabbal.",
        group: "Desszert",
        price: 1190,
        hasChildrenServingSize: false,
        extras: [
            {
                id: 1,
                name: "Vaníliás fagylalt",
                price: 200,
            },
            {
                id: 2,
                name: "Csokoládéöntet",
                price: 100,
            },
        ],
        packagingFee: 150,
    },
    {
        id: 63,
        name: "Mályvacukor",
        description: "Lédús gyümölcsökkel tálalt friss mályvacukor.",
        group: "Desszert",
        price: 990,
        hasChildrenServingSize: false,
        extras: [
            {
                id: 1,
                name: "Csokoládéöntet",
                price: 150,
            },
            {
                id: 2,
                name: "Karamellöntet",
                price: 100,
            },
        ],
        packagingFee: 150,
    },
    {
        id: 64,
        name: "Hasábburgonya",
        description: "Sült, ropogós hasábburgonya.",
        group: "Köret",
        price: 790,
        hasChildrenServingSize: true,
        priceOfChildrenServingSize: 500,
        packagingFee: 100,
    },
    {
        id: 65,
        name: "Rizs",
        description: "Friss főtt rizs.",
        group: "Köret",
        price: 550,
        hasChildrenServingSize: true,
        priceOfChildrenServingSize: 350,
        packagingFee: 100,
    },
    {
        id: 66,
        name: "Párolt zöldség",
        description: "Friss, párolt zöldségek.",
        group: "Köret",
        price: 690,
        hasChildrenServingSize: true,
        priceOfChildrenServingSize: 450,
        packagingFee: 100,
    },
    {
        id: 67,
        name: "Burgonyapüré",
        description: "Krémes burgonyapüré.",
        group: "Köret",
        price: 620,
        hasChildrenServingSize: true,
        priceOfChildrenServingSize: 400,
        packagingFee: 100,
    },
    {
        id: 68,
        name: "Kuszkusz",
        description: "Fűszeres kuszkusz köret.",
        group: "Köret",
        price: 480,
        hasChildrenServingSize: true,
        priceOfChildrenServingSize: 300,
        packagingFee: 100,
    },
    {
        id: 69,
        name: "Zöldségrizottó",
        description: "Friss zöldségekkel gazdagított rizottó.",
        group: "Köret",
        price: 760,
        hasChildrenServingSize: true,
        priceOfChildrenServingSize: 480,
        packagingFee: 100,
    },
    {
        id: 70,
        name: "Tarhonya",
        description: "Ropogós tarhonya köret.",
        group: "Köret",
        price: 580,
        hasChildrenServingSize: true,
        priceOfChildrenServingSize: 360,
        packagingFee: 100,
    },
    {
        id: 71,
        name: "Bulgur",
        description: "Könnyű bulgur köret.",
        group: "Köret",
        price: 630,
        hasChildrenServingSize: true,
        priceOfChildrenServingSize: 400,
        packagingFee: 100,
    },
    {
        id: 72,
        name: "Tört burgonya",
        description: "Tört burgonya vajjal és tejföllel.",
        group: "Köret",
        price: 670,
        hasChildrenServingSize: true,
        priceOfChildrenServingSize: 420,
        packagingFee: 100,
    },
    {
        id: 73,
        name: "Párolt rizs",
        description: "Ízletes párolt rizs.",
        group: "Köret",
        price: 520,
        hasChildrenServingSize: true,
        priceOfChildrenServingSize: 320,
        packagingFee: 100,
    },

    {
        id: 74,
        name: "Coca-Cola",
        description: "2,5dl",
        group: "Üdítő",
        price: 490,
        hasChildrenServingSize: false,
        packagingFee: 0,
    },
    {
        id: 75,
        name: "Pepsi",
        description: "2,5dl",
        group: "Üdítő",
        price: 490,
        hasChildrenServingSize: false,
        packagingFee: 0,
    },
    {
        id: 76,
        name: "Fanta",
        description: "2,5dl",
        group: "Üdítő",
        price: 490,
        hasChildrenServingSize: false,
        packagingFee: 0,
    },
    {
        id: 77,
        name: "Sprite",
        description: "2,5dl",
        group: "Üdítő",
        price: 490,
        hasChildrenServingSize: false,
        packagingFee: 0,
    },
    {
        id: 78,
        name: "Dr Pepper",
        description: "2,5dl",
        group: "Üdítő",
        price: 490,
        hasChildrenServingSize: false,
        packagingFee: 0,
    },
    {
        id: 79,
        name: "Schweppes",
        description: "2,5dl",
        group: "Üdítő",
        price: 490,
        hasChildrenServingSize: false,
        packagingFee: 0,
    },
    {
        id: 80,
        name: "Mirinda",
        description: "2,5dl",
        group: "Üdítő",
        price: 490,
        hasChildrenServingSize: false,
        packagingFee: 0,
    },
    {
        id: 81,
        name: "7UP",
        description: "2,5dl",
        group: "Üdítő",
        price: 490,
        hasChildrenServingSize: false,
        packagingFee: 0,
    },
];

export const DUMMY_FOOD_GROUPS: FoodGroup[] = [
    {
        id: 1,
        name: "Pizza",
        order: 1,
        imageURL:
            "https://firebasestorage.googleapis.com/v0/b/pizzeria-39338.appspot.com/o/foodgroups%2Fpizza.png?alt=media&token=5de448f4-a34a-4601-b7be-c8c3519a29eb",
    },
    {
        id: 2,
        name: "Leves",
        order: 3,
        imageURL:
            "https://firebasestorage.googleapis.com/v0/b/pizzeria-39338.appspot.com/o/foodgroups%2Fsoup.png?alt=media&token=1e1a40df-aac3-47f4-b5cf-e32b625bff80",
    },
    {
        id: 3,
        name: "Frissensült",
        order: 4,
        imageURL:
            "https://firebasestorage.googleapis.com/v0/b/pizzeria-39338.appspot.com/o/foodgroups%2Fchicken.png?alt=media&token=d0180cb8-4da1-47fe-953d-1457c8f57b41",
    },
    {
        id: 4,
        name: "Tészta",
        order: 6,
        imageURL:
            "https://firebasestorage.googleapis.com/v0/b/pizzeria-39338.appspot.com/o/foodgroups%2Fpasta.png?alt=media&token=b7af6a02-6297-4092-a62e-c38efce57c6b",
    },
    {
        id: 5,
        name: "Hamburger",
        order: 2,
        imageURL:
            "https://firebasestorage.googleapis.com/v0/b/pizzeria-39338.appspot.com/o/foodgroups%2Fhamburger.png?alt=media&token=b7835c9c-1fa8-4000-b0d9-814730d3c659",
    },
    {
        id: 6,
        name: "Saláta",
        order: 7,
        imageURL:
            "https://firebasestorage.googleapis.com/v0/b/pizzeria-39338.appspot.com/o/foodgroups%2Fsalad.png?alt=media&token=3c01b30a-163c-40bc-9b60-3b214fbc5723",
    },
    {
        id: 7,
        name: "Desszert",
        order: 8,
        imageURL:
            "https://firebasestorage.googleapis.com/v0/b/pizzeria-39338.appspot.com/o/foodgroups%2Fdessert.png?alt=media&token=0e06403b-2fc3-412d-b335-6591fb84bcf4",
    },
    {
        id: 8,
        name: "Köret",
        order: 5,
        imageURL:
            "https://firebasestorage.googleapis.com/v0/b/pizzeria-39338.appspot.com/o/foodgroups%2Ffried-potatoes.png?alt=media&token=02f33dec-1c45-493d-9fa0-5608a25e284c",
    },
    {
        id: 9,
        name: "Üdítő",
        order: 9,
        imageURL:
            "https://firebasestorage.googleapis.com/v0/b/pizzeria-39338.appspot.com/o/foodgroups%2Fcola.png?alt=media&token=9d440ad6-c0e1-4c40-89d0-4e83d5cab3c7",
    },
];
